DROP USER Q_<SYSID>_SVC
~
DROP LOGIN Q_<SYSID>_SVC
~
DROP ROLE Q_<SYSID>_CLI_ROLE
~
DROP ROLE Q_<SYSID>_SVC_ROLE
~
DROP SYNONYM Q_<SYSID>.GET_VALUE
~
DROP SYNONYM Q_<SYSID>.COMMIT_PROCESSING
~
DROP SYNONYM Q_<SYSID>.PUT_VALUE
~
DROP SYNONYM Q_<SYSID>.ROLLBACK_PROCESSING
~
DROP SYNONYM Q_<SYSID>.SEND_OUT_TRANS
~
DROP FUNCTION Q_<SYSID>.GET_STAGE_VALUE_3_10
~
DROP FUNCTION Q_<SYSID>.GET_OUT_VALUE_2_11
~
DROP FUNCTION Q_<SYSID>.GET_IN_VALUE_3_11
~
DROP FUNCTION Q_<SYSID>.GET_FINAL_STAGE_VALUE_1_10
~
DROP PROCEDURE Q_<SYSID>.COMMIT_STAGE_PROCESSING_8
~
DROP PROCEDURE Q_<SYSID>.COMMIT_IN_PROCESSING_4
~
DROP PROCEDURE Q_<SYSID>.COMMIT_OUT_PROCESSING_3
~
DROP PROCEDURE Q_<SYSID>.PUT_STAGE_VALUE_11_1
~
DROP PROCEDURE Q_<SYSID>.PUT_IN_VALUE_9_1
~
DROP PROCEDURE Q_<SYSID>.PUT_OUT_VALUE_9_1
~
DROP PROCEDURE Q_<SYSID>.ROLLBACK_STAGE_PROCESSING_6
~
DROP PROCEDURE Q_<SYSID>.ROLLBACK_IN_PROCESSING_4
~
DROP PROCEDURE Q_<SYSID>.ROLLBACK_OUT_PROCESSING_4
~
DROP PROCEDURE Q_<SYSID>.CHANGE_IN_SUBQ_3
~
DROP PROCEDURE Q_<SYSID>.SEND_OUT_TRANS_1
~
DROP PROCEDURE Q_<SYSID>.MOVE_DATA_IN_TO_LOG
~
DROP PROCEDURE Q_<SYSID>.MOVE_DATA_OUT_TO_LOG
~
DROP PROCEDURE Q_<SYSID>.MOVE_STAGE_TO_LOG
~
DROP TABLE Q_<SYSID>.STAGES_MSG
~
DROP TABLE Q_<SYSID>.STAGES_DEPS
~
DROP TABLE Q_<SYSID>.STAGES
~
DROP TABLE Q_<SYSID>.STAGES_LOG
~
DROP TABLE Q_<SYSID>.STAGES_LOG_ARCHIVE
~
DROP TABLE Q_<SYSID>.STAGES_ERRORS
~
DROP TABLE Q_<SYSID>.DATA_IN_MSG
~
DROP TABLE Q_<SYSID>.DATA_IN
~
DROP TABLE Q_<SYSID>.DATA_IN_LOG
~
DROP TABLE Q_<SYSID>.DATA_IN_LOG_ARCHIVE
~
DROP TABLE Q_<SYSID>.DATA_IN_ERRORS
~
DROP TABLE Q_<SYSID>.DATA_OUT_MSG
~
DROP TABLE Q_<SYSID>.DATA_OUT
~
DROP TABLE Q_<SYSID>.DATA_OUT_LOG
~
DROP TABLE Q_<SYSID>.DATA_OUT_LOG_ARCHIVE
~
DROP TABLE Q_<SYSID>.DATA_OUT_ERRORS
~
DROP TABLE Q_<SYSID>.EXT_TYPES
~
DROP TABLE Q_<SYSID>.TYPES
~
DROP SCHEMA Q_<SYSID>
~