DROP PROCEDURE SEND_OUT_TRANS
~
DROP PROCEDURE GET_VALUE
~
DROP FUNCTION  PUT_VALUE
~
DROP PROCEDURE COMMIT_PROCESSING
~
DROP PROCEDURE ROLLBACK_PROCESSING
~
DROP PROCEDURE SEND_OUT_TRANS_1
~
DROP PROCEDURE GET_STAGE_VALUE_3_10
~
DROP PROCEDURE GET_OUT_VALUE_2_11
~
DROP PROCEDURE GET_IN_VALUE_3_11
~
DROP PROCEDURE GET_FINAL_STAGE_VALUE_1_10
~
DROP PROCEDURE COMMIT_STAGE_PROCESSING_8
~
DROP PROCEDURE COMMIT_IN_PROCESSING_4
~
DROP PROCEDURE COMMIT_OUT_PROCESSING_3
~
DROP FUNCTION PUT_STAGE_VALUE_11_1
~
DROP FUNCTION PUT_IN_VALUE_9_1
~
DROP FUNCTION PUT_OUT_VALUE_9_1
~
DROP PROCEDURE ROLLBACK_STAGE_PROCESSING_6
~
DROP PROCEDURE ROLLBACK_IN_PROCESSING_4
~
DROP PROCEDURE ROLLBACK_OUT_PROCESSING_4
~
DROP PROCEDURE CHANGE_IN_SUBQ_3
~
DROP FUNCTION MOVE_DATA_IN_TO_LOG
~
DROP FUNCTION MOVE_DATA_OUT_TO_LOG
~
DROP FUNCTION MOVE_STAGE_TO_LOG
~
DROP TABLE STAGES_MSG
~
DROP TABLE STAGES_DEPS
~
DROP TABLE STAGES
~
DROP TABLE STAGES_LOG
~
DROP TABLE STAGES_LOG_ARCHIVE
~
DROP TABLE STAGES_ERRORS
~
DROP TABLE DATA_IN_MSG
~
DROP TABLE DATA_IN
~
DROP TABLE DATA_IN_LOG
~
DROP TABLE DATA_IN_LOG_ARCHIVE
~
DROP TABLE DATA_IN_ERRORS
~
DROP TABLE DATA_OUT_MSG
~
DROP TABLE DATA_OUT
~
DROP TABLE DATA_OUT_LOG
~
DROP TABLE DATA_OUT_LOG_ARCHIVE
~
DROP TABLE DATA_OUT_ERRORS
~
DROP TABLE EXT_TYPES
~
DROP TABLE TYPES
~
DROP USER 'Q_<SYSID>_SVC'
~
